# Generated by Django 2.2.3 on 2020-10-19 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20201015_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='exemptCSRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='longtermgoals',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.Course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='blackboardLink',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='longtermgoals',
            unique_together=set(),
        ),
    ]
