# Generated by Django 2.2.3 on 2020-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200922_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completedVark',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='varkA',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='varkK',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='varkR',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='varkV',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True),
        ),
    ]
