# Generated by Django 2.2.3 on 2020-10-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20201019_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='dateAdded',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='week',
        ),
        migrations.AlterField(
            model_name='resource',
            name='blackboardLink',
            field=models.URLField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
