# Generated by Django 2.2.3 on 2020-09-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20200925_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastModified', models.DateTimeField(null=True)),
                ('passFail', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.AssessmentItem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.Student')),
            ],
        ),
    ]
