# Generated by Django 3.1 on 2020-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='choice_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='upload',
            new_name='path',
        ),
        migrations.RemoveField(
            model_name='course',
            name='votes',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='week',
            field=models.IntegerField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
