# Generated by Django 2.2.3 on 2020-09-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200907_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(default='Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
