# Generated by Django 2.2.3 on 2020-09-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200914_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffcourse',
            old_name='student',
            new_name='staff',
        ),
    ]
