# Generated by Django 2.2.3 on 2020-09-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20200907_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=2),
        ),
    ]
