# Generated by Django 2.2.3 on 2020-09-22 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isDate', models.BooleanField(default=False)),
                ('date', models.DateTimeField(null=True)),
                ('dateDescription', models.CharField(max_length=255)),
                ('isPassFail', models.BooleanField(default=False)),
                ('weight', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Database.Student'),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
