# Generated by Django 2.2.3 on 2020-09-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VarkResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('V', models.FloatField()),
                ('A', models.FloatField()),
                ('R', models.FloatField()),
                ('K', models.FloatField()),
            ],
        ),
    ]
