# Generated by Django 2.2.3 on 2020-09-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VARK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varkresult',
            name='A',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='varkresult',
            name='K',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='varkresult',
            name='R',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='varkresult',
            name='V',
            field=models.CharField(max_length=5),
        ),
    ]
